import { CommunityMember } from "@/app/types"

export const members: CommunityMember[] = [
  {
    id: 1,
    name: "Dev Kim",
    role: "Full Stack Developer",
    interests: ["GPT-4", "Web Development", "Startup"],
    location: "Seoul",
    experience: "3 years",
    avatar: "/placeholder.svg?height=80&width=80",
    status: "online",
    projects: 12,
    connections: 45,
  },
  {
    id: 2,
    name: "Designer Park",
    role: "UX/UI Designer",
    interests: ["AI Design", "Prototyping", "User Experience"],
    location: "Busan",
    experience: "5 years",
    avatar: "/placeholder.svg?height=80&width=80",
    status: "online",
    projects: 8,
    connections: 67,
  },
  {
    id: 3,
    name: "Planner Lee",
    role: "Product Manager",
    interests: ["AI Strategy", "Business Model", "Data Analysis"],
    location: "Daegu",
    experience: "4 years",
    avatar: "/placeholder.svg?height=80&width=80",
    status: "just now",
    projects: 15,
    connections: 89,
  },
  {
    id: 4,
    name: "Marketer Choi",
    role: "Growth Marketer",
    interests: ["AI Marketing", "Content", "Growth Hacking"],
    location: "Incheon",
    experience: "2 years",
    avatar: "/placeholder.svg?height=80&width=80",
    status: "online",
    projects: 6,
    connections: 34,
  },
  {
    id: 5,
    name: "Data Jung",
    role: "Data Scientist",
    interests: ["Machine Learning", "Deep Learning", "Data Visualization"],
    location: "Gwangju",
    experience: "6 years",
    avatar: "/placeholder.svg?height=80&width=80",
    status: "online",
    projects: 20,
    connections: 112,
  },
  {
    id: 6,
    name: "Founder Han",
    role: "Startup CEO",
    interests: ["AI Business", "Investment", "Team Building"],
    location: "Daejeon",
    experience: "7 years",
    avatar: "/placeholder.svg?height=80&width=80",
    status: "just now",
    projects: 3,
    connections: 156,
  },
] 